### ISSUE TITLE
大佬 感谢你的贡献，有一点小小建议

### ISSUE THREAD

**Issue by user1121114685** [cuiqingandroid/CharlesZH#3]
## 1.运行汉化程序可以使用 批量命令。并且不需要安装 java sdk 这样方便每个人直接使用。      
 `Z:\jdk-16.0.2\bin\java.exe -jar E:\桌面文件存放\CharlesZH.jar`    

[绿色sdk下载地址](https://download.oracle.com/otn-pub/java/jdk/16.0.2%2B7/d4a915d82b4c4fbb9bde534da945d746/jdk-16.0.2_windows-x64_bin.zip)

**Comment by cuiqingandroid** [comment]
感谢你的建议
1. 等大部分内容汉化完成后，在release的时候同时打包jre运行环境
2. 其实可以自动识别charles的安装目录，直接替换。在windows上需要管理员权限，mac上还没试过

由于charles是java开发的，所以汉化大部分工作是修改java字节码，目前go还没有比较成熟的java字节码修改库。所以如果想用go语言重构，可能需要开发一个go语言识别java字节码及编译的功能模块

**Comment by user1121114685** [comment]
感谢大佬回复！java确实我也帮不上忙。只能幸苦大佬了
